apiVersion: fleet.squaremo.dev/v1alpha1
kind: Module
metadata:
  name: podinfo
  namespace: default
spec:
  selector: {}
  sync:
    source:
      git:
        url: https://github.com/richardcase/podinfo
        version:
          tag: v0.1.0
    package:
      kustomize:
        path: ./kustomize
