---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: fleeet-control
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./module/config/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: fleeet-config
