---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: fleet-objects
  namespace: flux-system
spec:
  dependsOn:
  - name: fleeet-control
  interval: 1m0s
  path: ./fleet
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system